appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime)|%(executionTime) ms|%(category)|connection %(connectionId)|%(sqlSingleLine)
dateformat=yyyy-MM-dd HH:mm:ss.SSS
excludecategories=debug,result,resultset,batch
